<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="QuestPDF" Version="2025.1.1" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Datos\SistemaVentas.Datos.csproj" />
    <ProjectReference Include="..\Entidades\SistemaVentas.Entidades.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Servicios\" />
  </ItemGroup>

</Project>
