<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>SistemadeVentas.Presentacion.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entidades\SistemaVentas.Entidades.csproj" />
    <ProjectReference Include="..\Negocio\SistemaVentas.Negocio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utilidades\" />
  </ItemGroup>

</Project>